UniversityStudentsApp/UniversityStudentsApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityStudentsApp.Data;
using UniversityStudentsApp.Models;
using UniversityStudentsApp.ViewModels;

namespace UniversityStudentsApp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly UniversityStudentsAppContext _context;

        public CoursesController(UniversityStudentsAppContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index(string courseTitle , int courseSemester, string courseProgramme)
        {
            IQueryable<Course> courses = _context.Courses.AsQueryable();
            IQueryable<string> titleQuery = _context.Courses
                .OrderBy(m => m.Title).Select(m => m.Title).Distinct();

            IQueryable<int> semesterQuery = _context.Courses
                .OrderBy(m => m.Semester).Select(m => m.Semester).Distinct();

            IQueryable<string> programmeQuery = _context.Courses
                .OrderBy(m => m.Programme).Select(m => m.Programme).Distinct();

            if (!string.IsNullOrEmpty(courseTitle))
            {
                courses = courses.Where(x => x.Title == courseTitle);
            }
            if (courseSemester != 0)
            {
                courses = courses.Where(x => x.Semester == courseSemester);
            }
            if (!string.IsNullOrEmpty(courseProgramme))
            {
                courses = courses.Where(x => x.Programme == courseProgramme);
            }

            courses = courses.Include(m => m.FirstTeacher).ThenInclude(m => m.FirstTeacherCourses);
            courses = courses.Include(m => m.SecondTeacher).ThenInclude(m => m.SecondTeacherCourses);
            courses = courses.Include(m => m.Students).ThenInclude(m => m.Student);

            var courseFilterVM = new CourseFilterViewModel
            {
                Titles = new SelectList(await titleQuery.ToListAsync()),
                Semesters = new SelectList(await semesterQuery.ToListAsync()),
                Programmes = new SelectList(await programmeQuery.ToListAsync()),
                Courses = await courses.ToListAsync()

            };
            return View(courseFilterVM);
            
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FirstName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FirstName", course.SecondTeacherId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FirstName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FirstName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
    }
}

UniversityStudentsApp/UniversityStudentsApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityStudentsApp.Data;
using UniversityStudentsApp.Models;
using UniversityStudentsApp.ViewModels;

namespace UniversityStudentsApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly UniversityStudentsAppContext _context;

        public TeachersController(UniversityStudentsAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index(string teacherName, string teacherDegree, string teacherAcRank)
        {
            IQueryable<Teacher> professors = _context.Teacher.AsQueryable();

            IQueryable<String> teacherDegreeQuery = _context.Teacher
                .OrderBy(m => m.Degree).Select(m => m.Degree).Distinct();

            IQueryable<String> teacherAcRankQuery = _context.Teacher
                .OrderBy(m => m.AcademicRank).Select(m => m.AcademicRank).Distinct();

            if (!String.IsNullOrEmpty(teacherName))
            {
                professors = professors.Where(s => s.FirstName.Contains(teacherName) || s.LastName.Contains(teacherName));
            }

            if (!String.IsNullOrEmpty(teacherDegree))
            {
                professors = professors.Where(x => x.Degree == teacherDegree);
            }
            if (!String.IsNullOrEmpty(teacherAcRank))
            {
                professors = professors.Where(x => x.AcademicRank == teacherAcRank);
            }

            professors = professors.Include(m => m.FirstTeacherCourses)
                                    .Include(m => m.SecondTeacherCourses);


            var teacherFilterViewModel = new TeacherFilterViewModel
            {
                Professors = await professors.ToListAsync(),
                Degrees = new SelectList(await teacherDegreeQuery.ToListAsync()),
                AcademicRanks = new SelectList(await teacherAcRankQuery.ToListAsync())

            };

            return View(teacherFilterViewModel);
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .Include(p => p.FirstTeacherCourses)
                .Include(p => p.SecondTeacherCourses)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }
    }
}

UniversityStudentsApp/UniversityStudentsApp/Views/Courses/Create.cshtml
@model UniversityStudentsApp.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programme" class="control-label"></label>
                <input asp-for="Programme" class="form-control" />
                <span asp-validation-for="Programme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EducationLevel" class="control-label"></label>
                <input asp-for="EducationLevel" class="form-control" />
                <span asp-validation-for="EducationLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstTeacherId" class="control-label"></label>
                <select asp-for="FirstTeacherId" class ="form-control" asp-items="ViewBag.FirstTeacherId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SecondTeacherId" class="control-label"></label>
                <select asp-for="SecondTeacherId" class ="form-control" asp-items="ViewBag.SecondTeacherId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityStudentsApp/UniversityStudentsApp/Views/Courses/Delete.cshtml
@model UniversityStudentsApp.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstTeacher.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondTeacher.FirstName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UniversityStudentsApp/UniversityStudentsApp/Views/Courses/Details.cshtml
@model UniversityStudentsApp.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
       <dd class="col-sm-10">
        @if (Model.FirstTeacher != null)
        {
            <a asp-controller="Professors" asp-action="Details" asp-route-id="@Model.FirstTeacherId">@Html.DisplayFor(model => model.FirstTeacher.FullName)</a>
        }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd class="col-sm-10">
            @if (Model.SecondTeacher != null)
            {
                <a asp-controller="Professors" asp-action="Details" asp-route-id="@Model.SecondTeacherId">@Html.DisplayFor(model => model.SecondTeacher.FullName)</a>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UniversityStudentsApp/UniversityStudentsApp/Views/Courses/Edit.cshtml
@model UniversityStudentsApp.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programme" class="control-label"></label>
                <input asp-for="Programme" class="form-control" />
                <span asp-validation-for="Programme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EducationLevel" class="control-label"></label>
                <input asp-for="EducationLevel" class="form-control" />
                <span asp-validation-for="EducationLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstTeacherId" class="control-label"></label>
                <select asp-for="FirstTeacherId" class="form-control" asp-items="ViewBag.FirstTeacherId"></select>
                <span asp-validation-for="FirstTeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondTeacherId" class="control-label"></label>
                <select asp-for="SecondTeacherId" class="form-control" asp-items="ViewBag.SecondTeacherId"></select>
                <span asp-validation-for="SecondTeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityStudentsApp/UniversityStudentsApp/Views/Courses/Index.cshtml
@*@@model IEnumerable<UniversityStudentsApp.Models.Course>*@
@model UniversityStudentsApp.ViewModels.CourseFilterViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Courses</h1>

<form asp-controller="Courses" asp-action="Index" method="get">
    <p>
        Title:
        <select asp-for="CourseTitle" asp-items="Model.Titles">
            <option value="">All</option>
        </select>
        Semester:
        <select asp-for="CourseSemester" asp-items="Model.Semesters">
            <option value="">All</option>
        </select>
        Programme:
        <select asp-for="CourseProgramme" asp-items="Model.Programmes">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].EducationLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].FirstTeacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].SecondTeacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Courses) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Programme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationLevel)
            </td>
            <td>
                @if (item.FirstTeacherId != null)
                {
                    <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.FirstTeacherId"> @Html.DisplayFor(modelItem => item.FirstTeacher.FullName)</a>
                }

            </td>
            <td>
                @if (item.SecondTeacherId != null)
                {
                    <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.SecondTeacherId"> @Html.DisplayFor(modelItem => item.SecondTeacher.FullName)</a>
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>